### ISSUE TITLE
PDF generation fails

### ISSUE THREAD

**Issue by aquatix** [mgaitan/sphinxcontrib-mermaid#30]
Sphinx has changed the logging object somewhat, so we get unexpected breakage when the plugin calls "self.builder.warn()". This breaks latexpdf output though:

Exception occurred:
  File "/[REDACTED]/lib/python3.6/site-packages/sphinxcontrib/mermaid.py", line 180, in render_mm
    self.builder.warn('Mermaid SVG support is experimental')
AttributeError: 'LaTeXBuilder' object has no attribute 'warn'

A fix release would be much appreciated! :)

**Comment by Abrosimov-a-a** [comment]
I cinfirm it too.

```
# Sphinx version: 2.0.1
# Python version: 3.7.3 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   ...
#   resolving references...
#   готово
#   writing...
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (2.0.1) from python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.intersphinx (2.0.1) from python3.7/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (2.0.1) from python3.7/site-packages/sphinx/ext/todo.py
#   sphinxcontrib.mermaid (2.0.1) from python3.7/site-packages/sphinxcontrib/mermaid.py
Traceback (most recent call last):
  File "python3.7/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "python3.7/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "python3.7/site-packages/sphinx/builders/__init__.py", line 321, in build_update
    self.build(['__all__'], to_build)
  File "python3.7/site-packages/sphinx/builders/__init__.py", line 389, in build
    self.write(docnames, list(updated_docnames), method)
  File "python3.7/site-packages/sphinx/builders/latex/__init__.py", line 280, in write
    docwriter.write(doctree, destination)
  File "python3.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "python3.7/site-packages/sphinx/writers/latex.py", line 253, in translate
    self.document.walkabout(visitor)
  File "python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "python3.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 3 more times]
  File "python3.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "python3.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "python3.7/site-packages/sphinxcontrib/mermaid.py", line 314, in latex_visit_mermaid
    render_mm_latex(self, node, node['code'], node['options'])
  File "python3.7/site-packages/sphinxcontrib/mermaid.py", line 285, in render_mm_latex
    fname, outfn = render_mm(self, code, options, 'pdf', prefix)
  File "python3.7/site-packages/sphinxcontrib/mermaid.py", line 180, in render_mm
    self.builder.warn('Mermaid SVG support is experimental')
AttributeError: 'LaTeXBuilder' object has no attribute 'warn'
```

**Comment by Abrosimov-a-a** [comment]
Martin,

Can you update package in PyPi repo?

**Comment by neelgala** [comment]
could you please update  pypi?
Thanks

**Comment by mgaitan** [comment]
@neelgala @Abrosimov-a-a just released a new version with latests changes. 

please confirm me if this error still happens

**Comment by timkpaine** [comment]
Closing as fixed. Current code uses Sphinx logging instead of the removed builder.warn API, and PDF output is covered by the current LaTeX rendering path.
