### ISSUE TITLE
some APIs are removed in Sphinx 4.0 version

### ISSUE THREAD

**Issue by MegChai** [mgaitan/sphinxcontrib-mermaid#72]
such as ``sphinx.util.osutil.ENOENT``:

https://github.com/mgaitan/sphinxcontrib-mermaid/blob/07f9d4316f76d249f89d9b6fd289b8918b426344/sphinxcontrib/mermaid.py#L27

It was removed now and we can use `errno.ENOENT` instead of it. 

refs : https://github.com/sphinx-doc/sphinx/blob/master/doc/extdev/deprecated.rst

**Comment by hoefling** [comment]
To reproduce:
```sh
$ pip install sphinx sphinxcontrib-mermaid
$ python -c "import sphinxcontrib.mermaid"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tst/lib64/python3.9/site-packages/sphinxcontrib/mermaid.py", line 27, in <module>
    from sphinx.util.osutil import ensuredir, ENOENT
ImportError: cannot import name 'ENOENT' from 'sphinx.util.osutil' (/tmp/tst/lib64/python3.9/site-packages/sphinx/util/osutil.py)
```

**Comment by hoefling** [comment]
Workaround:
```py
import errno
import sphinx.util.osutil
sphinx.util.osutil.ENOENT = errno.ENOENT
```
in `conf.py`.
